import React, { useState, useEffect } from 'react';
import PredictionsDirectory from './components/PredictionsDirectory';
import EDAView from './components/EDAView';
import { Stethoscope, Activity, BarChart2, AlertCircle } from 'lucide-react';
import './index.css';

export default function App() {
  const [activeTab, setActiveTab] = useState('eda');
  const [data, setData] = useState([]);
  // Canonical train-learned F1-max thresholds from machineLearning/models/thresholds.json.
  // Defaults are fallbacks only — replaced once the fetch resolves on first render.
  const [thresholds, setThresholds] = useState({ admission: 0.6873, readmission: 0.3394 });
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // In a real hospital, this would fetch from a secure API endpoint
    // For this prototype, we simulate fetching the massive static JSON generated by the batch ML script
    Promise.all([
      fetch('/data/dashboard_payload.json').then(r => r.json()),
      fetch('/data/thresholds.json').then(r => r.ok ? r.json() : null)
    ])
      .then(([payload, thr]) => {
        setData(payload);
        if (thr && typeof thr.admission === 'number' && typeof thr.readmission === 'number') {
          setThresholds(thr);
        }
        setLoading(false);
      })
      .catch(err => {
        console.error("Failed to load dashboard assets:", err);
        setLoading(false);
      });
  }, []);

  if (loading) {
    return (
      <div className="app-container">
        <div className="loading-screen">
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '1rem' }}>
            <Activity color="var(--primary)" size={48} className="fast-spin" />
            <h2>Loading Full Cohort Predictions (62k+ patients)...</h2>
            <p style={{ color: 'var(--text-muted)' }}>Parsing machine learning inferences & SHAP values</p>
          </div>
        </div>
      </div>
    );
  }



  return (
    <div className="app-container">
      {/* Top Navbar */}
      <header className="header" style={{ padding: '1.5rem 3rem' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
          <div style={{ 
            background: 'linear-gradient(135deg, var(--primary), #a78bfa)', 
            padding: '0.6rem', 
            borderRadius: '12px',
            boxShadow: '0 4px 15px rgba(59, 130, 246, 0.4)'
          }}>
            <Stethoscope color="white" />
          </div>
          <div>
            <h1 style={{ fontSize: '1.35rem', margin: '0' }}>Clinical Data & Prediction Insights</h1>
            <p style={{ margin: '0', fontSize: '0.85rem' }}>AI-Assisted Admission Explorer</p>
          </div>
        </div>

        <nav className="nav-links" style={{ padding: '0.5rem', background: 'var(--bg-surface)' }}>
          <button 
            className={`nav-btn ${activeTab === 'eda' ? 'active' : ''}`}
            onClick={() => setActiveTab('eda')}
            style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', padding: '0.6rem 1.5rem' }}
          >
            <Activity size={16} /> Dataset EDAs
          </button>
          <button 
            className={`nav-btn ${activeTab === 'predictions' ? 'active' : ''}`}
            onClick={() => setActiveTab('predictions')}
            style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', padding: '0.6rem 1.5rem' }}
          >
            <BarChart2 size={16} /> Patient Triage Pipeline
          </button>
        </nav>

        <div style={{ display: 'flex', alignItems: 'center', gap: '1.5rem' }}>
          <span style={{ fontSize: '0.9rem', color: 'var(--text-muted)', fontWeight: '500' }}>Analyzed: 62,135 Profiles</span>
        </div>
      </header>

      {/* Main View Area */}
      <main className="main-content" style={{ padding: '3rem' }}>
        {data.length > 0 ? (
          activeTab === 'predictions' ? <PredictionsDirectory data={data} thresholds={thresholds} /> : <EDAView data={data} thresholds={thresholds} />
        ) : (
          <div style={{ textAlign: 'center', padding: '5rem', color: 'var(--text-muted)' }}>
            <AlertCircle size={48} color="var(--danger)" style={{ marginBottom: '1rem', opacity: 0.8 }} />
            <h2>No batch results available</h2>
            <p>Ensure the Python script has successfully written dashboard_payload.json</p>
          </div>
        )}
      </main>
    </div>
  );
}
