import React, { useState, useEffect } from 'react';
import PredictionsDirectory from './components/PredictionsDirectory';
import PatientDetail from './components/PatientDetail';
import EDAView from './components/EDAView';
import { Stethoscope, LogIn, Activity, AlertCircle, BarChart2 } from 'lucide-react';
import './index.css';

export default function App() {
  const [activeTab, setActiveTab] = useState('eda');
  const [selectedPatient, setSelectedPatient] = useState(null);
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // In a real hospital, this would fetch from a secure API endpoint
    // For this prototype, we simulate fetching the massive static JSON generated by the batch ML script
    fetch('/data/dashboard_payload.json')
      .then(res => res.json())
      .then(json => {
        setData(json);
        setLoading(false);
      })
      .catch(err => {
        console.error("Failed to load dashboard payload:", err);
        setLoading(false);
      });
  }, []);

  if (loading) {
    return (
      <div className="app-container">
        <div className="loading-screen">
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '1rem' }}>
            <Activity color="var(--primary)" size={48} className="fast-spin" />
            <h2>Loading Full Cohort Predictions (62k+ patients)...</h2>
            <p style={{ color: 'var(--text-muted)' }}>Parsing machine learning inferences & SHAP values</p>
          </div>
        </div>
      </div>
    );
  }

  // Handle navigation
  const renderContent = () => {
    if (selectedPatient) {
      return <PatientDetail patient={selectedPatient} onBack={() => setSelectedPatient(null)} />;
    }

    if (activeTab === 'predictions') {
      return <PredictionsDirectory data={data} onSelectPatient={setSelectedPatient} />;
    } else if (activeTab === 'eda') {
      return <EDAView data={data} />;
    }
  };

  return (
    <div className="app-container">
      {/* Top Navbar */}
      <header className="header">
        <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
          <div style={{ 
            background: 'linear-gradient(135deg, var(--primary), #a78bfa)', 
            padding: '0.5rem', 
            borderRadius: '10px',
            boxShadow: '0 4px 15px rgba(59, 130, 246, 0.4)'
          }}>
            <Stethoscope color="white" />
          </div>
          <div>
            <h1 style={{ fontSize: '1.25rem', margin: '0' }}>Clinical Data & Prediction Insights</h1>
            <p style={{ margin: '0', fontSize: '0.8rem' }}>AI-Assisted Admission Explorer</p>
          </div>
        </div>

        <nav className="nav-links">
          <button 
            className={`nav-btn ${activeTab === 'eda' && !selectedPatient ? 'active' : ''}`}
            onClick={() => { setActiveTab('eda'); setSelectedPatient(null); }}
            style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}
          >
            <Activity size={16} /> Dataset EDAs
          </button>
          <button 
            className={`nav-btn ${activeTab === 'predictions' && !selectedPatient ? 'active' : ''}`}
            onClick={() => { setActiveTab('predictions'); setSelectedPatient(null); }}
            style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}
          >
            <BarChart2 size={16} /> Patient Triage Pipeline
          </button>
        </nav>

        <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
          <span style={{ fontSize: '0.9rem', color: 'var(--text-muted)' }}>Analyzed: 62,135 Profiles</span>
          <button style={{ 
            background: 'rgba(255,255,255,0.05)', 
            border: '1px solid var(--border-light)', 
            color: 'var(--text-main)', 
            padding: '0.5rem 1rem', 
            borderRadius: '8px',
            cursor: 'pointer',
            display: 'flex',
            alignItems: 'center',
            gap: '0.5rem'
          }}>
            <LogIn size={16} /> Clinician Export
          </button>
        </div>
      </header>

      {/* Main View Area */}
      <main className="main-content">
        {data.length > 0 ? (
          renderContent()
        ) : (
          <div style={{ textAlign: 'center', padding: '5rem', color: 'var(--text-muted)' }}>
            <AlertCircle size={48} color="var(--danger)" style={{ marginBottom: '1rem', opacity: 0.8 }} />
            <h2>No batch results available</h2>
            <p>Ensure the Python script has successfully written dashboard_payload.json</p>
          </div>
        )}
      </main>
    </div>
  );
}
